### ISSUE TITLE
`rcli` cannot find R after `rcli install <version>`

### ISSUE THREAD

**Issue by schelhorn** [pat-s/rcli#16]
**Describe the bug**
Cool tool, thanks for making it! 
Bug: When running the Homebrew version of rcli 0.2.0 on macOS Monterey, rcli uses macOS's "find" which results in "find: illegal option -- m"

**To Reproduce**

```shell
brew tap pat-s/rcli 
brew install rcli
(works normally)
rcli install 4.1.2
(works normally)
rcli switch 4.1.2
/usr/local/bin/rcli: line 161: R: command not found
/usr/local/bin/rcli: line 162: R: command not found
/usr/local/bin/rcli: line 295: R: command not found
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
Password:
```

**Expected behavior**
rcli should switch to the installed R 4.1.2

**Operating system (please complete the following information):**
macOS Monterey 12.1

**Additional context**
```shell
which find
/usr/bin/find

```

**Comment by pat-s** [comment]
Thanks. 

Can you see if you can reproduce this with v0.5?
Is there any reason you're using v0.2 instead of v0.5?

**Comment by schelhorn** [comment]
Hmm, it is unclear to me which version I really have. I installed rcli using homebrew yesterday using:

```shell
brew tap pat-s/rcli 
brew install rcli
``` 

Asking rcli for its version says:

```shell
rcli --version
0.2.0
```

However, asking homebrew for an upgrade says:

```shell
brew upgrade rcli
Warning: pat-s/rcli/rcli v0.5.0 already installed
```

and asking homebrew:

```shell
brew info rcli
Command line tool to install and switch between R versions
https://github.com/pat-s/rcli
/usr/local/Cellar/rcli/v0.5.0 (3 files, 33.9KB) *
  Built from source on 2022-01-22 at 22:57:33
From: https://github.com/pat-s/homebrew-rcli/blob/HEAD/Formula/rcli.rb
License: LGPL-3.0
```

When looking into https://github.com/pat-s/rcli/releases/download/v0.5.0/rcli I have seen that release still has thw wrong version number in the code:

```shell
elif [[ $1 == "--version" || $1 == "-v" ]]; then
  echo "0.2.0"
  exit 0
```

so I *guess* I already have 0.5.0 running?

**Comment by pat-s** [comment]
Thanks!

> is unclear to me which version I really have. I installed rcli using homebrew yesterday using:

I forgot to bump the recorded version, you are on `v0.5.0` and the output of `rcli --version` is buggy. Will fix that ASAP.

So when you do 

```
rcli install 4.1.2
```

you don't need to add another `rcli switch <version>`, `rcli install` already does that.

> Is it a requirement of rcli that R should have been installed before? Because the homebrew recipe does not contain that requirement, and the documentation does not mention it, I believe.

Yes it is and I also check for this in 

https://github.com/pat-s/rcli/blob/947f9b9d45efd9418bfb6e0802892d03681bd92e/rcli.sh#L89-L93

which already should have prevented running `rcli install 4.1.2` - but it seems this is not enough.
Did you really not have R installed in any other way? I've just tried this, i.e. `brew remove --cask r` and then ran `rcli install 4.1.2` and I got

```
rcli requires R to be installed (which is not the case it seems). Please first install R, e.g. via homebrew by calling brew install --cask r or by using the CRAN GUI installer.
```

I think checking if `which R` does not return anything is safer than looking at `/Library/Frameworks/R.framework` as it will also detect non-CRAN installations.

> Also, by the way, I did not have /usr/sbin in my $PATH at first, so rcli could not find the installer command and errored out when installing the new R version that I wanted to install using rcli. Perhaps that is something you could check for as well?

Interesting - thanks for the report. This is important and should be asserted for. Which shell did you use? `zsh`, `bash` or something else?

---

I'll look into adding the cask dependency `r` to the formula, this might clear some issues not having the R cask installed.

**Comment by pat-s** [comment]
Unfortunately brew formulas cannot depend on brew casks :/
Hence I need to stay with manual checks to test for its presence.

In fact, `rcli` does not necessarily require the homebrew `r` cask but only that the CRAN installer was used to install R (into `/Library/Frameworks/R.framework`). 

If I read your OP again, I think the issue could be that `/usr/local/bin` was not in your $PATH and hence `R` could not be found (because `rcli install` linked `R` to `/usr/local/bin/R`).
Whereas you had in fact R installed at `/Library/Frameworks/R.framework` before.
Could that be the case? If so, the question how you started your shell would become important again.

I am running tests on GitHub actions with a vanilla macOS setup (at least that's what I think) and there it appears `/usr/local/bin` and `/usr/sbin` are in $PATH by default.

**Comment by schelhorn** [comment]
> Interesting - thanks for the report. This is important and should be asserted for. Which shell did you use? zsh, bash or something else?

I am using `bash` at the moment.

> If I read your OP again, I think the issue could be that /usr/local/bin was not in your $PATH and hence R could not be found (because rcli install linked R to /usr/local/bin/R). Whereas you had in fact R installed at /Library/Frameworks/R.framework before. Could that be the case? 

Well deducted; yes, I believe that may have been the case.

> I am running tests on GitHub actions with a vanilla macOS setup (at least that's what I think) and there it appears /usr/local/bin and /usr/sbin are in $PATH by default.

Apparently my configuration is non-standard; I have added these directories to my `PATH` now to be safe - thanks. Please feel free to close the issue.

(As a last sidenote: I really see rcli analogously to `pyenv` for Python; `pyenv` has additional command modes that you could take for inspiration, see https://github.com/pyenv/pyenv)

**Comment by pat-s** [comment]
> Apparently my configuration is non-standard; I have added these directories to my PATH now to be safe - thanks. Please feel free to close the issue.

What would be of interest for me is *how* and *why* your config is non-standard to prevent other users from hitting the same issue.
While I've now included assertions for `/usr/local/bin` and `/usr/bin` early in `rcli` which should result in an descriptive error message, I am also curious on a personal level.

> (As a last sidenote: I really see rcli analogously to pyenv for Python; pyenv has additional command modes that you could take for inspiration, see pyenv/pyenv)

Thanks! I did not really had this on my radar but this could be helpful for further development.
