### ISSUE TITLE
rcli should list installable R versions

### ISSUE THREAD

**Issue by schelhorn** [pat-s/rcli#32]
Currently, there is no way for users to list installable versions of R; instead, users have to use external information to install the latest version. It would be great if:

- `rcli install` would list the list of installable R versions, or alternatively a new verb is created for that (such as `rcli available`, or similar).
- `rcli install latest` would install the latest R version available for the current architecture.

Thanks!

**Comment by pat-s** [comment]
To install the latest version you can already to `rcli install release`. The same works for `devel`.

In principal all R versions available from CRAN can be installed. I am not sure how useful such a command would be given the already existing `release` alias.
If a specific R version should be installed, the version needs to be passed anyhow. 
To check every once in a while if there is a new R version, you could just do call `rcli install release` again.

What do you think?

**Comment by pat-s** [comment]
@schelhorn I'll close here as I think at least one part of your request is already available and I am not sure if I want to support the other (= listing of installable R versions). 

Feel free to re-open if needed!
