### ISSUE TITLE
a small typo in the [website](https://rcli.pat-s.me/)

### ISSUE THREAD

**Issue by Eyayaw** [pat-s/rcli#36]
* a simple way to switch between different installed R versions without **l~o~osing** the packages of the previous version (applies to macOS only)

**Comment by pat-s** [comment]
Thanks! 

Just FYI: I think it should be possible to propose change requests yourself using gitbook when clicking on the "Gitbook" menu in the bottom left. Requires an account though.

Anyhow thanks again!
