### ISSUE TITLE
Similar tool "rim"

### ISSUE THREAD

**Issue by schelhorn** [pat-s/rcli#44]
This just serves as a FYI that there seems to be a package similar to your from the rlib folks called `rim` - perhaps it could serve as a source of inspiration (and vice versa, of course)? See: https://github.com/r-lib/rim

**Comment by pat-s** [comment]
Thanks, I am aware of `rim` already 🙂 we've been already in contact but for now it seems both tools are moving forward on their own.

**Comment by schelhorn** [comment]
Very good!
